### ISSUE TITLE
Sorting issue in case of a inner table

### ISSUE THREAD

**Issue by shettyabhishek** [wenzhixin/blog#9]
Hi ,
    I am using the bootstrap table plugin. And in my requirement I have a inner table inside a given table. The inner table and the parent table are both bootstrap table . The issue I am facing is - when i try to sort the inner table the sort function for both the inner table and the parent table gets  triggered, as a result the inner table collapses .

I feel this is happening because of these below lines of code 
 
this.$container.off('click', '.th-inner').on('click', '.th-inner', function (event) {
            if (that.options.sortable && $(this).parent().data().sortable) {
                that.onSort(event);
            }
        });

![table view](https://cloud.githubusercontent.com/assets/8736042/9107972/c90ccef4-3c48-11e5-9214-6832054373ad.PNG)

On clicking on the inner table header, the inner table collapses. Its because the sorting for the parent table gets fired 

![after collapse](https://cloud.githubusercontent.com/assets/8736042/9108052/506851fc-3c49-11e5-8165-1fb6a4204a96.PNG)

This being a very critical issue , would really appreciate your inputs.

**Comment by shettyabhishek** [comment]
The version I am using is - version: 1.8.1

**Comment by wenzhixin** [comment]
Please submit the bug to [bootstrap-table](https://github.com/wenzhixin/bootstrap-table) repo.
